import { createFileRoute } from "@tanstack/react-router";
import { ChevronDown, CircleHelp } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/quiz/AppShell";
import { Panel } from "@/components/quiz/ui";

export const Route = createFileRoute("/aide")({ component: HelpPage });
const FAQ = [["Comment gagner de l'XP ?", "Termine des quiz. Les modes Chrono, Défi aléatoire et Haïti Quest donnent des multiplicateurs d'XP."],["Comment fonctionne le combo ?", "Deux bonnes réponses de suite activent un bonus. Les paliers x3 et x5 augmentent fortement les points."],["Ma progression est-elle sauvegardée ?", "Oui. La version actuelle sauvegarde la progression localement sur ton appareil."],["Comment débloquer Haïti Quest ?", "Les zones demandent certains niveaux. Termine les missions pour progresser et marquer les zones comme conquises."],["Puis-je jouer sans pression ?", "Oui. Le mode Entraînement n'a pas de chrono et affiche une explication après chaque réponse."]];
function HelpPage() { const [open, setOpen] = useState(0); return <AppShell><div className="mx-auto max-w-2xl space-y-5"><header><p className="font-display text-xs uppercase tracking-[0.35em] text-accent">Support</p><h1 className="mt-2 text-2xl font-black">Centre d'aide</h1><p className="mt-1 text-sm text-muted-foreground">Quelques réponses avant de repartir à l'assaut.</p></header><Panel className="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary/15 text-accent"><CircleHelp /></span><div><p className="font-display font-bold">FAQ Quiz Time</p><p className="text-xs text-muted-foreground">Les règles essentielles du jeu.</p></div></div>{FAQ.map(([q, a], i) => <div key={q} className="border-t border-border/60 py-4"><button onClick={() => setOpen(open === i ? -1 : i)} className="flex w-full items-center justify-between text-left font-semibold"><span>{q}</span><ChevronDown className={`size-4 transition ${open === i ? "rotate-180 text-accent" : ""}`} /></button>{open === i && <p className="mt-2 pr-6 text-sm leading-6 text-muted-foreground">{a}</p>}</div>)}</Panel></div></AppShell>; }
