import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, Copy, Home, MessageCircle, Share2, Swords, Trophy, Users, Zap } from "lucide-react";
import { AppShell } from "@/components/quiz/AppShell";
import { Panel, PrimaryButton, StatTile } from "@/components/quiz/ui";
import { useGame } from "@/lib/game-store";
import { copyShareText, shareQuiz, shareQuizWhatsApp } from "@/lib/sharing";
import { useState } from "react";

export const Route = createFileRoute("/resultats")({ component: ResultsPage });
function ResultsPage() {
  const navigate = useNavigate();
  const { lastResult, player, level } = useGame();
  const [copied, setCopied] = useState(false);
  if (!lastResult) return <AppShell><Panel className="mx-auto max-w-xl p-8 text-center"><h1 className="text-2xl font-black">Aucun résultat récent</h1><Link to="/jouer" className="mt-5 inline-block text-accent">Commencer une partie →</Link></Panel></AppShell>;
  const percent = Math.round((lastResult.correct / Math.max(1, lastResult.total)) * 100);
  const payload = { score: lastResult.score, correct: lastResult.correct, total: lastResult.total, combo: lastResult.bestCombo, xp: lastResult.xpGained, level, name: player.name };
  const replay = () => { const search = { mode: lastResult.config.mode, ...(lastResult.config.subject !== "haiti" ? { subject: lastResult.config.subject } : {}) }; navigate({ to: "/jouer/preparation", search, replace: true }); };
  const goLobby = () => navigate({ to: "/", replace: true });
  const copy = async () => { const ok = await copyShareText(payload); if (ok) { setCopied(true); window.setTimeout(() => setCopied(false), 1800); } };
  return <AppShell><div className="mx-auto max-w-3xl space-y-5"><button onClick={goLobby} className="tap glass rounded-full p-2" aria-label="Retour au lobby"><ArrowLeft className="size-4" /></button><Panel glow className="p-6 text-center sm:p-8"><div className="mx-auto grid size-20 place-items-center rounded-3xl bg-[image:var(--gradient-primary)] text-primary-foreground"><Trophy className="size-10" /></div><p className="mt-4 font-display text-xs uppercase tracking-[0.3em] text-accent">Mission terminée</p><h1 className="mt-2 text-3xl font-black">{percent >= 80 ? "Excellent run !" : "Mission accomplie !"}</h1><p className="mt-2 text-sm text-muted-foreground">{lastResult.config.mode === "haiti" ? "Haïti Quest" : lastResult.config.mode}</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><StatTile label="Score" value={lastResult.score} icon={<Zap className="size-4" />} /><StatTile label="Réussite" value={`${percent}%`} icon={<CheckCircle2 className="size-4" />} accent="success" /><StatTile label="Combo" value={`x${lastResult.bestCombo}`} /><StatTile label="XP gagné" value={`+${lastResult.xpGained}`} /></div></Panel>

    <Panel className="border-accent/20 bg-accent/5 p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-accent/15 text-accent"><Share2 className="size-5" /></div><div><p className="font-display text-sm font-black uppercase tracking-wider">Ton score mérite d'être vu 👀</p><p className="text-xs text-muted-foreground">Partage ton résultat ou défie un ami. Les boutons de jeu restent juste en dessous.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><button onClick={() => shareQuizWhatsApp(payload)} className="tap flex items-center justify-center gap-2 rounded-2xl bg-[#25D366] px-4 py-3 font-display text-xs font-black uppercase tracking-wider text-white transition-transform hover:-translate-y-0.5"><MessageCircle className="size-4" /> WhatsApp</button><button onClick={() => shareQuiz(payload, true)} className="tap flex items-center justify-center gap-2 rounded-2xl bg-[image:var(--gradient-primary)] px-4 py-3 font-display text-xs font-black uppercase tracking-wider text-primary-foreground transition-transform hover:-translate-y-0.5"><Swords className="size-4" /> Défier un ami</button><button onClick={copy} className="tap flex items-center justify-center gap-2 rounded-2xl glass px-4 py-3 font-display text-xs font-black uppercase tracking-wider transition-transform hover:-translate-y-0.5"><Copy className="size-4" /> {copied ? "Copié !" : "Copier le partage"}</button></div></Panel>

    <div className="grid gap-3 sm:grid-cols-2"><PrimaryButton onClick={replay}>Rejouer</PrimaryButton><button onClick={goLobby} className="tap glass flex items-center justify-center rounded-2xl px-5 py-4 font-display text-xs font-bold uppercase tracking-[0.18em]">Retour au lobby <Home className="ml-2 size-4" /></button></div>{lastResult.newBadges.length > 0 && <Panel className="p-5"><p className="font-display text-sm font-bold">🎖️ Nouvelles récompenses</p><p className="mt-1 text-sm text-muted-foreground">{lastResult.newBadges.length} badge(s) débloqué(s). Va dans Récompenses pour les voir.</p></Panel>}
    <Panel className="p-5"><div className="flex items-center gap-3"><Users className="size-5 text-accent" /><div><p className="font-display text-sm font-bold">Fais découvrir QuizTime Go</p><p className="text-xs text-muted-foreground">Invite tes amis à jouer et lancez-vous des défis.</p></div></div><button onClick={() => shareQuizWhatsApp(payload, true)} className="tap mt-4 w-full rounded-2xl glass px-4 py-3 text-sm font-bold">📲 Inviter mes amis sur WhatsApp</button></Panel>
    </div></AppShell>;
}
