/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router. It is updated here so the repository stays runnable until the next route generation.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JouerIndexRouteImport } from './routes/jouer.index'
import { Route as JouerPreparationRouteImport } from './routes/jouer.preparation'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as RecompensesRouteImport } from './routes/recompenses'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as HaitiQuestRouteImport } from './routes/haiti-quest'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as AideRouteImport } from './routes/aide'

const IndexRoute = IndexRouteImport.update({ id:'/', path:'/', getParentRoute:()=>rootRouteImport } as any)
const JouerIndexRoute = JouerIndexRouteImport.update({ id:'/jouer/', path:'/jouer/', getParentRoute:()=>rootRouteImport } as any)
const JouerPreparationRoute = JouerPreparationRouteImport.update({ id:'/jouer/preparation', path:'/jouer/preparation', getParentRoute:()=>rootRouteImport } as any)
const QuizRoute = QuizRouteImport.update({ id:'/quiz', path:'/quiz', getParentRoute:()=>rootRouteImport } as any)
const ResultatsRoute = ResultatsRouteImport.update({ id:'/resultats', path:'/resultats', getParentRoute:()=>rootRouteImport } as any)
const ClassementRoute = ClassementRouteImport.update({ id:'/classement', path:'/classement', getParentRoute:()=>rootRouteImport } as any)
const RecompensesRoute = RecompensesRouteImport.update({ id:'/recompenses', path:'/recompenses', getParentRoute:()=>rootRouteImport } as any)
const ProfilRoute = ProfilRouteImport.update({ id:'/profil', path:'/profil', getParentRoute:()=>rootRouteImport } as any)
const HaitiQuestRoute = HaitiQuestRouteImport.update({ id:'/haiti-quest', path:'/haiti-quest', getParentRoute:()=>rootRouteImport } as any)
const ParametresRoute = ParametresRouteImport.update({ id:'/parametres', path:'/parametres', getParentRoute:()=>rootRouteImport } as any)
const AideRoute = AideRouteImport.update({ id:'/aide', path:'/aide', getParentRoute:()=>rootRouteImport } as any)

export interface FileRoutesByFullPath { '/':typeof IndexRoute; '/jouer/':typeof JouerIndexRoute; '/jouer/preparation':typeof JouerPreparationRoute; '/quiz':typeof QuizRoute; '/resultats':typeof ResultatsRoute; '/classement':typeof ClassementRoute; '/recompenses':typeof RecompensesRoute; '/profil':typeof ProfilRoute; '/haiti-quest':typeof HaitiQuestRoute; '/parametres':typeof ParametresRoute; '/aide':typeof AideRoute }
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById { __root__:typeof rootRouteImport; '/':typeof IndexRoute; '/jouer/':typeof JouerIndexRoute; '/jouer/preparation':typeof JouerPreparationRoute; '/quiz':typeof QuizRoute; '/resultats':typeof ResultatsRoute; '/classement':typeof ClassementRoute; '/recompenses':typeof RecompensesRoute; '/profil':typeof ProfilRoute; '/haiti-quest':typeof HaitiQuestRoute; '/parametres':typeof ParametresRoute; '/aide':typeof AideRoute }
export interface FileRouteTypes { fileRoutesByFullPath:FileRoutesByFullPath; fullPaths:keyof FileRoutesByFullPath; fileRoutesByTo:FileRoutesByTo; to:keyof FileRoutesByTo; id:keyof FileRoutesById; fileRoutesById:FileRoutesById }
export interface RootRouteChildren { IndexRoute:typeof IndexRoute; JouerIndexRoute:typeof JouerIndexRoute; JouerPreparationRoute:typeof JouerPreparationRoute; QuizRoute:typeof QuizRoute; ResultatsRoute:typeof ResultatsRoute; ClassementRoute:typeof ClassementRoute; RecompensesRoute:typeof RecompensesRoute; ProfilRoute:typeof ProfilRoute; HaitiQuestRoute:typeof HaitiQuestRoute; ParametresRoute:typeof ParametresRoute; AideRoute:typeof AideRoute }

declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport};
  '/jouer/':{id:'/jouer/';path:'/jouer/';fullPath:'/jouer/';preLoaderRoute:typeof JouerIndexRouteImport;parentRoute:typeof rootRouteImport};
  '/jouer/preparation':{id:'/jouer/preparation';path:'/jouer/preparation';fullPath:'/jouer/preparation';preLoaderRoute:typeof JouerPreparationRouteImport;parentRoute:typeof rootRouteImport};
  '/quiz':{id:'/quiz';path:'/quiz';fullPath:'/quiz';preLoaderRoute:typeof QuizRouteImport;parentRoute:typeof rootRouteImport};
  '/resultats':{id:'/resultats';path:'/resultats';fullPath:'/resultats';preLoaderRoute:typeof ResultatsRouteImport;parentRoute:typeof rootRouteImport};
  '/classement':{id:'/classement';path:'/classement';fullPath:'/classement';preLoaderRoute:typeof ClassementRouteImport;parentRoute:typeof rootRouteImport};
  '/recompenses':{id:'/recompenses';path:'/recompenses';fullPath:'/recompenses';preLoaderRoute:typeof RecompensesRouteImport;parentRoute:typeof rootRouteImport};
  '/profil':{id:'/profil';path:'/profil';fullPath:'/profil';preLoaderRoute:typeof ProfilRouteImport;parentRoute:typeof rootRouteImport};
  '/haiti-quest':{id:'/haiti-quest';path:'/haiti-quest';fullPath:'/haiti-quest';preLoaderRoute:typeof HaitiQuestRouteImport;parentRoute:typeof rootRouteImport};
  '/parametres':{id:'/parametres';path:'/parametres';fullPath:'/parametres';preLoaderRoute:typeof ParametresRouteImport;parentRoute:typeof rootRouteImport};
  '/aide':{id:'/aide';path:'/aide';fullPath:'/aide';preLoaderRoute:typeof AideRouteImport;parentRoute:typeof rootRouteImport};
}}

const rootRouteChildren:RootRouteChildren = { IndexRoute, JouerIndexRoute, JouerPreparationRoute, QuizRoute, ResultatsRoute, ClassementRoute, RecompensesRoute, ProfilRoute, HaitiQuestRoute, ParametresRoute, AideRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr:true; router:Awaited<ReturnType<typeof getRouter>>; config:Awaited<ReturnType<typeof startInstance.getOptions>> } }
